# Generated by Django 2.0.4 on 2018-04-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter Business Name', max_length=200)),
                ('description', models.CharField(help_text='Enter Business Description', max_length=200)),
                ('address', models.CharField(help_text='Enter Business Address', max_length=200)),
                ('val_comp', models.BooleanField()),
                ('valuation', models.IntegerField(help_text='Number of Views', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Enter Input Type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Enter this year minus the entry year')),
                ('amount', models.IntegerField(help_text='Enter amount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.Business')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contacts', models.IntegerField(help_text='Number of Contact')),
                ('views', models.IntegerField(help_text='Number of Views')),
                ('expiration', models.DateTimeField()),
                ('intiation', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter Owner Name', max_length=200)),
                ('phone', models.CharField(help_text='Enter Owner Phone', max_length=200)),
                ('email', models.CharField(help_text='Enter Owner Email', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.Business')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Interested', to='demoapp.User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contacted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Contacted', to='demoapp.User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.Listing'),
        ),
        migrations.AddField(
            model_name='business',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Broker', to='demoapp.User'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Owner', to='demoapp.User'),
        ),
    ]
