# Generated by Django 2.0.4 on 2018-04-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20180421_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='valuation',
            field=models.IntegerField(help_text='Valuation', null=True),
        ),
    ]
