# Generated by Django 2.0.4 on 2018-04-21 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20180421_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('mon', 'Monthly'), ('year', 'Yearly')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='function',
            field=models.CharField(choices=[('br', 'Broker'), ('buy', 'Buyer'), ('own', 'Owner')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
