# Generated by Django 2.0.4 on 2018-04-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_valuation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuation',
            name='growth',
        ),
    ]
